### PR TITLE
Documentation - Multimedia player support for youtu.be URLs

### PR DESCRIPTION
**Pull request by duboisp**

### CODE REVIEW

**Comment by EricDunsworth** [comment]
@duboisp I had initially considered modifying the multimedia player's documentation as a part of wet-boew/wet-boew#7835, but decided against it since I felt the pre-existing documentation was already worded plainly-enough that it could conceivably apply to any kind of YouTube URL (short or long).

Maybe there'd be value in just keeping the existing wording as-is and adding parentheses at the end of it containing samples of both kinds of URLs?

Example:
> Add a ``source`` element to the ``video`` element with ``type="video/youtube"`` and the ``src`` attribute being the URL of the video (e.g. ``https://www.youtube.com/watch?v=9znKJqnFuuY`` or ``https://youtu.be/9znKJqnFuuY``).

@duboisp @LaurentGoderre @nschonni Thoughts?

**Comment by nschonni** [comment]
If there is anything to add to the doc, i think it would just be a code example rather than spelling out the alternate versions (youtu.be, youtube-nocookie.com, etc).

**Comment by duboisp** [comment]
@EricDunsworth I followed @nschonni suggestion and I added a example instead of spelling out the alternate version.

**Comment by EricDunsworth** [comment]
@duboisp Thanks :)!

So as for next steps, I guess I can just merge in this PR, then hard reset my branch to @duboisp's commit (to prevent GitHub's merge commit from appearing as a part of wet-boew/wet-boew#7835's commits)?

@nschonni @duboisp Thoughts? Would you mind if wet-boew/wet-boew#7835 brings in 2 commits? Usually I try to always stick to 1 commit per PR, but this is kind of an exceptional case since it has multiple committers.

**Comment by nschonni** [comment]
You can do a Merge and Squash from the UI now. It's under the arrow in the Merge button. That will avoid the extra commit.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: EricDunsworthSent: Friday, January 20, 2017 4:12 PMTo: EricDunsworth/wet-boewReply To: EricDunsworth/wet-boewCc: Nick Schonning; MentionSubject: Re: [EricDunsworth/wet-boew] Documentation - Multimedia player support for youtu.be URLs (#1)@duboisp Thanks :)!
So as for next steps, I guess I can just merge in this PR, then hard reset my branch to @duboisp's commit (to prevent GitHub's merge commit from appearing as a part of wet-boew/wet-boew#7835's commits)?
@nschonni @duboisp Thoughts? Would you mind if wet-boew/wet-boew#7835 brings in 2 commits? Usually I try to always stick to 1 commit per PR, but this is kind of an exceptional case since it has multiple committers.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EricDunsworth/wet-boew","title":"EricDunsworth/wet-boew","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/EricDunsworth/wet-boew"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EricDunsworth in #1: @duboisp Thanks :)!\r\n\r\nSo as for next steps, I guess I can just merge in this PR, then hard reset my branch to @duboisp's commit (to prevent GitHub's merge commit from appearing as a part of wet-boew/wet-boew#7835's commits)?\r\n\r\n@nschonni @duboisp Thoughts? Would you mind if wet-boew/wet-boew#7835 brings in 2 commits? Usually I try to always stick to 1 commit per PR, but this is kind of an exceptional case since it has multiple committers."}],"action":{"name":"View Pull Request","url":"https://github.com/EricDunsworth/wet-boew/pull/1#issuecomment-274181219"}}}

**Comment by EricDunsworth** [comment]
@nschonni Oh, cool :)! Never noticed that before. I'll go with that.

**Pull request merged**
